# Generated by Django 5.2.1 on 2025-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='cover-picture.png', upload_to='cover_images'),
        ),
    ]
