# Generated by Django 5.2.1 on 2025-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='cover-picture.jpg', upload_to='cover_images'),
        ),
    ]
